.PHONY : build rebuild clean

default :
	@echo "======================================="
	@echo "Please use 'make build' command to build it.."
	@echo "Please use 'make rebuild' command to build it.."
	@echo "Please use 'make clean' command to clean all."
	@echo "======================================="

# 当您使用Make build、rebuild、clean时, 这里会被调用.
# 所以, 您应该定义一套合理的脚本用于3rd内的库进行维护.

build:
	@echo "Done."

rebuild:
	@echo "Done."

clean:
	@echo "Done."
