return {
  -- 文本格式
  ['xml'] = 'application/xml',
  ['htm'] = 'text/html',
  ['html'] = 'text/html',
  ['shtml'] = 'text/html',
  ['xhtml'] = 'application/xhtml+xml',
  ['txt']  = 'text/plain',
  ['css']  = 'text/css',
  ['json'] = 'application/json',
  ['rtf'] = 'application/rtf',
  ['ogx'] = 'application/ogg',
  -- 图片格式
  ['bmp']  = 'image/bmp',
  ['png']  = 'image/png',
  ['gif']  = 'image/gif',
  ['jpeg'] = 'image/jpeg',
  ['jpg']  = 'image/jpeg',
  ['ico']  = 'image/x-icon',
  ['tif']  = 'image/tiff',
  ['tiff'] = 'image/tiff',
  ['svg'] = 'image/svg+xml',
  -- 音频
  ['au'] = 'audio/basic',
  ['wav'] = 'audio/wav',
  ['acc'] = 'audio/aac',
  ['mp3'] = 'audio/mpeg',
  ['oga'] = 'audio/ogg',
  -- 视频
  ['avi'] = 'video/x-msvideo',
  ['mpa'] = 'video/mpeg',
  ['mpe'] = 'video/mpeg',
  ['mp2'] = 'video/mpeg',
  ['mpeg'] = 'video/mpeg',
  ['mp4'] = 'audio/mp4',
  ['qt'] = 'video/mpeg',
  ['mov'] = 'video/mpeg',
  ['webm'] = 'video/webm',
  ['flv'] = 'video/x-flv',
  ['m4v'] = 'video/x-m4v',
  ['3gp'] = 'video/3gpp',
  ['3gpp'] = 'video/3gpp',
  ['ts'] = 'video/mp2t',
  ['ogv'] = 'video/ogg',
  -- 文档
  ['csv'] = 'text/csv',
  ['dot'] = 'application/msword',
  ['doc'] = 'application/msword',
  ['mdb'] = 'application/x-msaccess',
  ['xls'] = 'application/vnd.ms-excel',
  ['ppt'] = 'application/vnd.ms-powerpoint',
  ['chm'] = 'application/vnd.ms-htmlhelp',
  ['xlsx'] = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ['docx'] = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  ['pptx'] = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  ['pdf'] = 'application/pdf',
  -- 密匙
  ['der'] = 'application/x-x509-ca-cert',
  ['cer'] = 'application/x-x509-ca-cert',
  ['pem'] = 'application/x-x509-ca-cert',
  ['crt'] = 'application/x-x509-ca-cert',
  ['p10'] = 'application/pkcs10',
  ['p12'] = 'application/x-pkcs12',
  ['pfx'] = 'application/x-pkcs12',
  ['p7c'] = 'application/x-pkcs7-mime',
  ['p7m'] = 'application/x-pkcs7-mime',
  ['p7b'] = 'application/x-pkcs7-certificates',
  ['spc'] = 'application/x-pkcs7-certificates',
  ['p7r'] = 'application/x-pkcs7-certreqresp',
  ['p7s'] = 'application/x-pkcs7-signature',
  -- 压缩文件
  ['7z'] = 'application/x-7z-compressed',
  ['zip'] = 'application/zip',
  ['gz'] = 'application/x-gzip',
  ['tar'] = 'application/x-tar',
  ['gtar'] = 'application/x-gtar',
  ['tgz'] = 'application/x-compressed',
  ['rar'] = 'application/x-rar-compressed',
  -- 源文件
  ['c'] = 'text/plain',
  ['cxx'] = 'text/plain',
  ['cpp'] = 'text/plain',
  ['h'] = 'text/plain',
  ['hpp'] = 'text/plain',
  ['py'] = 'text/plain',
  ['cs'] = 'text/plain',
  ['lua'] = 'text/plain',
  ['js'] = 'application/javascript',
  -- TODO
}