return {
  -- 文本格式
  ['xml'] = 'application/xml',
  ['htm'] = 'text/html',
  ['html'] = 'text/html',
  ['shtml'] = 'text/html',
  ['mml'] = 'text/mathml',
  ['xhtml'] = 'application/xhtml+xml',
  ['txt']  = 'text/plain',
  ['htc'] = 'text/x-component',
  ['wml'] = 'text/vnd.wap.wml',
  ['css']  = 'text/css',
  ['rss'] = 'application/rss+xml',
  ['json'] = 'application/json',
  ['rtf'] = 'application/rtf',
  ['atom'] = 'application/atom+xml',
  ['ogx'] = 'application/ogg',
  -- 图片格式
  ['bmp']  = 'image/bmp',
  ['png']  = 'image/png',
  ['gif']  = 'image/gif',
  ['jpeg'] = 'image/jpeg',
  ['jpg']  = 'image/jpeg',
  ['ico']  = 'image/x-icon',
  ['tif']  = 'image/tiff',
  ['tiff'] = 'image/tiff',
  ['svg'] = 'image/svg+xml',
  -- 音频
  ['au'] = 'audio/basic',
  ['wav'] = 'audio/wav',
  ['acc'] = 'audio/aac',
  ['mp3'] = 'audio/mpeg',
  ['oga'] = 'audio/ogg',
  -- 视频
  ['avi'] = { type = 'video/x-msvideo' },
  ['mpa'] = { type = 'video/mpeg' },
  ['mpe'] = { type = 'video/mpeg'},
  ['mp2'] = { type = 'video/mpeg' },
  ['mpeg'] = { type = 'video/mpeg' },
  ['mp4'] = { type = 'audio/mp4' },
  ['qt'] = { type = 'video/mpeg' },
  ['mov'] = { type = 'video/mpeg' },
  ['webm'] = { type = 'video/webm' },
  ['flv'] = { type = 'video/x-flv' },
  ['m4v'] = { type = 'video/x-m4v' },
  ['ts'] = { type = 'video/mp2t' },
  ['ogv'] = { type = 'video/ogg' },
  -- 文档
  ['csv'] = { type = 'text/csv'},
  ['dot'] = { type = 'application/msword' },
  ['doc'] = { type = 'application/msword' },
  ['mdb'] = { type = 'application/x-msaccess' },
  ['xls'] = { type = 'application/vnd.ms-excel' },
  ['ppt'] = { type = 'application/vnd.ms-powerpoint' },
  ['chm'] = { type = 'application/vnd.ms-htmlhelp' },
  ['xlsx'] = { type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' },
  ['docx'] = { type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' },
  ['pptx'] = { type = 'application/vnd.openxmlformats-officedocument.presentationml.presentation' },
  ['pdf'] = 'application/pdf',
  -- 密匙
  ['der'] = 'application/x-x509-ca-cert',
  ['cer'] = 'application/x-x509-ca-cert',
  ['pem'] = 'application/x-x509-ca-cert',
  ['crt'] = 'application/x-x509-ca-cert',
  ['p10'] = 'application/pkcs10',
  ['p12'] = 'application/x-pkcs12',
  ['pfx'] = 'application/x-pkcs12',
  ['p7c'] = 'application/x-pkcs7-mime',
  ['p7m'] = 'application/x-pkcs7-mime',
  ['p7b'] = 'application/x-pkcs7-certificates',
  ['spc'] = 'application/x-pkcs7-certificates',
  ['p7r'] = 'application/x-pkcs7-certreqresp',
  ['p7s'] = 'application/x-pkcs7-signature',
  -- 压缩文件
  ['7z'] = { type = 'application/x-7z-compressed' },
  ['zip'] = { type = 'application/zip' },
  ['gz'] = { type = 'application/x-gzip' },
  ['tar'] = { type = 'application/x-tar' },
  ['gtar'] = { type = 'application/x-gtar' },
  ['tgz'] = { type = 'application/x-compressed' },
  ['rar'] = { type = 'application/x-rar-compressed' },
  -- 源文件
  ['c'] = 'text/plain',
  ['cxx'] = 'text/plain',
  ['cpp'] = 'text/plain',
  ['h'] = 'text/plain',
  ['hpp'] = 'text/plain',
  ['py'] = 'text/plain',
  ['cs'] = 'text/plain',
  ['lua'] = 'text/plain',
  ['js'] = 'application/javascript',
  -- TODO
}